FROM scratch
ADD bclinux-7.7-docker.tar.xz /

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="BCLinux Base Image" \
    org.label-schema.vendor="BCLinux" \
    org.label-schema.license="GPLv2" \
    org.label-schema.build-date="20230505"

CMD ["/bin/bash"]

